[wokwi]
version = 1
elf = ".pio/build/esp32doit-devkit-v1/firmware.elf"
firmware = ".pio/build/esp32doit-devkit-v1/firmware.bin"
gdbServerPort=3333

# Port forwarding from virtual network to real
[[net.forward]]
from = "localhost:80"
to = "target:80"