// This file is generated by `build_file_system_image.py`. Do not edit it. Run Build Filesystem Image to update it.
// Source Files: `web/src/index.html` and its dependencies
const char index_html_gz[] = {
    b'alma'
};